name: Publish to Powershell Gallery

on: [workflow_dispatch]

jobs:
  Publish:
    runs-on: windows-latest
    
    steps:
    - name: Publish
      shell: pwsh
      env:
        PSGALLERY_API_KEY: ${{ secrets.PSGALLERY_API_KEY }}
      run: | 
        echo "Publishing package SecureStrings..."
        Publish-PSResource -Path .\Modules\SecureStrings\ -ApiKey "$env:PSGALLERY_API_KEY" -Verbose
